### ISSUE TITLE
Question: Synchronization and Fault-tolerance

### ISSUE THREAD

**Issue by meyerdan** [jsam/miniflow#1]
first of all, I think this project is super awesome. I like that everything is basically in one file and the golang syntax slowly grows on me :)

My first question in about fork/join (or fan-out, fan-in as named in the code, if I understand correctly):
I am looking at at the [fanIn](https://github.com/jsam/miniflow/blob/master/workflow.go#L119) function: if I understand correctly, this is invoked whenever a token is received through go channel which is, I soppose, connected through nats? My next assumption is that the "WaitGroup" allows us to synchronize tokens, correct? How do we need to think about this in a miniflow cluster? Will the nats kind of "shard" the tokens belonging to the same workflow intance that they go to the same miniflow instance? Or are you thinking about a distributed locking service? - I am just interested, this is the kind of stuff I like to think about :)

Second Question: assume that te processing of a token fails (program is killed, whatever). Will the nats then redeliver the message and by this the system will "re-try"?

**Comment by jsam** [comment]
Hey Daniel, thank you very much for the feedback and sorry for delayed reply.

There are two modes of operations. You can execute the workflow on a single node without using any kind of external messaging. In this case every 2 connected tasks will have exactly 1 channel between two tasks. In one task that channel will be outs (out going channel) and in other it will be ins (in going channel), or in other words one will send and other will receive.

Now in distributed mode, philosophy is "bring your own messaging". As an example I used NATS messaging (cause it integrates very nicely with go channels) but you could use any other messaging system user would like (we just have to write connectors). Now in this mode by default, every 2 connected tasks  will have exactly 2 channels which are going to be connected by external PubSub 
(which will have common "<relation_name>:<workflow_ID>""). This way we ensure that tasks are connected throughout different workflows.

Now every channel has concept of condition which is going to decide if this token can take this route (channel) in the graph or not. This is not fully supported yet! :oops:

The fanIn pattern is very simple way to multiplex channels (aggregate all "ins" into 1 channel) on which then I can listen to. With that function I make sure to aggregate all “ins” channels into 1. The WaitGroup there is to ensure that all listeners for every registered "ins" channelis fully started before returning the unified/multiplexed channel.
 
Now on clustering topic. I have not yet fully decided how to do clustering (including how to resolve retries and locking), I do have couple of ideas which I’m trying to evaluate. I'll keep you updated on those =))

**Comment by jsam** [comment]
Ok, I reworked most of the stuff. So everything we discussed above is no longer true. With the new structure, there is support for replaying the message in case of disaster and clustering+locking are resolved with QueueGroups. I will close the issue, if you have any more question feel free to open new one ;)

Best,
Sam.
